<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="MAIN" Id="{e6fc0db3-25a2-4645-a13b-e62a8719f101}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// programa en 0//


//segundo cambio en el POU//

// cambio numero 3// 


// cambio numero 4//


//cambio umero 5///]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>